Document: bgp-extrapolator
Title: Debian bgp-extrapolator Manual
Author: <insert document author here>
Abstract: This manual describes what bgp-extrapolator is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/bgp-extrapolator/bgp-extrapolator.sgml.gz

Format: postscript
Files: /usr/share/doc/bgp-extrapolator/bgp-extrapolator.ps.gz

Format: text
Files: /usr/share/doc/bgp-extrapolator/bgp-extrapolator.text.gz

Format: HTML
Index: /usr/share/doc/bgp-extrapolator/html/index.html
Files: /usr/share/doc/bgp-extrapolator/html/*.html
